//! Integration tests using `ffmpeg`/`cwebp`-produced reference WebP files.
//!
//! Each test generates a small reference image into `/tmp` (when one of
//! the encoders is available) and decodes it through the public
//! [`oxideav_webp::decode_webp`] entry point.
//!
//! All tests degrade gracefully — if neither tool is installed, the test
//! prints a skip message and returns success (mirrors the pattern used in
//! `oxideav-opus/tests/roundtrip.rs`).

use std::path::Path;
use std::process::Command;

use oxideav_webp::decode_webp;

const FFMPEG: &str = "/usr/bin/ffmpeg";
const CWEBP: &str = "/usr/bin/cwebp";

fn ffmpeg_available() -> bool {
    Path::new(FFMPEG).exists()
}

fn cwebp_available() -> bool {
    Path::new(CWEBP).exists()
}

/// Run a command, return true on success.
fn run(cmd: &str, args: &[&str]) -> bool {
    Command::new(cmd)
        .args(args)
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Generate (or reuse) a 64x64 lossy WebP at the given path. Tries
/// ffmpeg's libwebp encoder first; returns the path on success, or `None`
/// if neither tool is available.
fn ensure_lossy_64() -> Option<&'static str> {
    let path = "/tmp/oxideav-webp-ref-lossy-64x64.webp";
    if Path::new(path).exists() {
        return Some(path);
    }
    if ffmpeg_available()
        && run(
            FFMPEG,
            &[
                "-y",
                "-hide_banner",
                "-loglevel",
                "error",
                "-f",
                "lavfi",
                "-i",
                "color=red:size=64x64",
                "-frames:v",
                "1",
                "-c:v",
                "libwebp",
                path,
            ],
        )
        && Path::new(path).exists()
    {
        return Some(path);
    }
    None
}

/// Generate (or reuse) a small lossless WebP. Tries cwebp first (with a
/// PNG generated by ffmpeg) and falls back to ffmpeg+libwebp. Returns the
/// path on success.
fn ensure_lossless_32() -> Option<&'static str> {
    let path = "/tmp/oxideav-webp-ref-lossless-32x32.webp";
    if Path::new(path).exists() {
        return Some(path);
    }
    // Path A: ffmpeg → PNG → cwebp -lossless.
    if ffmpeg_available() && cwebp_available() {
        let png = "/tmp/oxideav-webp-ref-32x32.png";
        if !Path::new(png).exists() {
            run(
                FFMPEG,
                &[
                    "-y",
                    "-hide_banner",
                    "-loglevel",
                    "error",
                    "-f",
                    "lavfi",
                    "-i",
                    "color=blue:size=32x32",
                    "-frames:v",
                    "1",
                    png,
                ],
            );
        }
        if Path::new(png).exists()
            && run(CWEBP, &["-quiet", "-lossless", png, "-o", path])
            && Path::new(path).exists()
        {
            return Some(path);
        }
    }
    // Path B: ffmpeg + libwebp -lossless 1.
    if ffmpeg_available()
        && run(
            FFMPEG,
            &[
                "-y",
                "-hide_banner",
                "-loglevel",
                "error",
                "-f",
                "lavfi",
                "-i",
                "color=blue:size=32x32",
                "-frames:v",
                "1",
                "-c:v",
                "libwebp",
                "-lossless",
                "1",
                path,
            ],
        )
        && Path::new(path).exists()
    {
        return Some(path);
    }
    None
}

#[test]
fn lossy_64x64_decodes_to_non_zero() {
    let Some(path) = ensure_lossy_64() else {
        eprintln!("skip: neither ffmpeg nor cwebp produced a lossy reference");
        return;
    };
    let bytes = std::fs::read(path).expect("read lossy ref");
    let img = decode_webp(&bytes).expect("decode lossy");
    assert_eq!(img.width, 64);
    assert_eq!(img.height, 64);
    assert_eq!(img.frames.len(), 1, "single-frame lossy still");
    let f = &img.frames[0];
    assert_eq!(f.rgba.len(), 64 * 64 * 4);

    // The reference is a uniform red field. We assert two minimum
    // properties — anything stronger has to wait for the inherited VP8
    // left-edge B_PRED bug to be fixed in `oxideav-vp8`:
    //
    //   1. The decoder produces non-zero pixel output (not stuck at 0).
    //   2. Every pixel has full alpha (lossy WebP without ALPH = opaque).
    //
    // The actual colour fidelity is currently degraded by the VP8 chroma
    // pipeline, so we don't assert on hue here.
    let mut nonzero_pixels = 0usize;
    for px in f.rgba.chunks_exact(4) {
        if px[0] != 0 || px[1] != 0 || px[2] != 0 {
            nonzero_pixels += 1;
        }
        assert_eq!(px[3], 0xff, "VP8 lossy WebP must produce opaque alpha");
    }
    assert!(
        nonzero_pixels > (64 * 64 / 2),
        "expected most pixels to have non-zero RGB; got {nonzero_pixels}/{}",
        64 * 64
    );
}

#[test]
fn lossless_32x32_decodes_to_blue() {
    let Some(path) = ensure_lossless_32() else {
        eprintln!("skip: neither ffmpeg nor cwebp produced a lossless reference");
        return;
    };
    let bytes = std::fs::read(path).expect("read lossless ref");
    let img = decode_webp(&bytes).expect("decode lossless");
    assert_eq!(img.width, 32);
    assert_eq!(img.height, 32);
    assert_eq!(img.frames.len(), 1);
    let f = &img.frames[0];
    assert_eq!(f.rgba.len(), 32 * 32 * 4);

    // Lossless reference: the source is `color=blue` which ffmpeg's PNG
    // pipeline renders to a uniform shade of blue. Lossless WebP must
    // round-trip that shade exactly — but ffmpeg's sRGB conversion of
    // "blue" may land slightly off from (0, 0, 255). So we assert:
    //
    //   * Every pixel is identical (lossless = no spatial variance).
    //   * The colour is predominantly blue (B > 200, R/G < 10).
    //   * Alpha is fully opaque.
    let first = (f.rgba[0], f.rgba[1], f.rgba[2], f.rgba[3]);
    assert!(
        first.2 > 200 && first.0 < 10 && first.1 < 10,
        "expected predominantly blue, got rgba={first:?}"
    );
    assert_eq!(first.3, 0xff, "alpha must be opaque");
    for (i, px) in f.rgba.chunks_exact(4).enumerate() {
        assert_eq!(
            (px[0], px[1], px[2], px[3]),
            first,
            "pixel {i} differs from first; lossless image must be uniform"
        );
    }
}
