//! MPEG audio (Layer I/II/III) file container.
//!
//! Despite the `mp3` module name, this demuxer covers all three MPEG
//! audio layers — `.mp1`, `.mp2`, and `.mp3` files are all raw streams
//! of MPEG audio frames, typically with an ID3v2 tag prefix and an
//! optional ID3v1 suffix, and they share the same 4-byte frame header
//! format. We read the first frame's layer field and select the matching
//! codec id (`mp1`, `mp2`, or `mp3`) so the registry can dispatch to the
//! right decoder.
//!
//! 1. Skips an ID3v2 prefix if present (extension supports CBR + VBR
//!    files generated by every common encoder).
//! 2. Probes the first valid frame to populate `CodecParameters` with
//!    sample rate + channel count + codec id (mp1/mp2/mp3).
//! 3. Emits each frame as one `Packet` (the downstream decoder consumes
//!    one frame per packet).
//!
//! ID3v1 trailer (last 128 bytes prefixed with `TAG`) is stopped on
//! cleanly when sync search hits end of file.

use std::io::{Read, Seek, SeekFrom};

use oxideav_container::{ContainerRegistry, Demuxer, ProbeData, ReadSeek};
use oxideav_core::{
    AttachedPicture, CodecId, CodecParameters, Error, MediaType, Packet, Result, SampleFormat,
    StreamInfo, TimeBase,
};

use crate::frame::parse_frame_header_any_layer;

/// Maximum bytes we'll scan looking for the first valid frame (covers a
/// 256 KB worst-case ID3v2 tag plus padding).
const MAX_HEADER_SCAN: usize = 1 << 18;

/// Maximum bytes we'll skip between two audio frames when hunting for
/// the next sync word. Covers mid-stream embedded tags, APE footers,
/// loose padding, and small desync caused by framing quirks. Large
/// enough to step over a 64 KB embedded APIC; small enough that we
/// don't pretend a runaway file has audio content when it doesn't.
const MAX_RESYNC_BYTES: usize = 64 * 1024;

pub fn register(reg: &mut ContainerRegistry) {
    reg.register_demuxer("mp3", open);
    reg.register_extension("mp3", "mp3");
    reg.register_extension("mp2", "mp3");
    reg.register_extension("mp1", "mp3");
    reg.register_probe("mp3", probe);
}

/// `ID3` magic at offset 0 (very common) OR an MPEG audio sync byte
/// pattern in the first ~256 bytes. The latter is the only signal for
/// raw MP3 files without ID3v2, which is why we look for the bit
/// pattern: byte 0 = 0xFF, byte 1 has the top 3 bits set
/// (0xE0..=0xFF). Even with that, sync alone is fragile, so we
/// confirm by parsing the next 4-byte header.
fn probe(p: &ProbeData) -> u8 {
    if p.buf.len() >= 10 && &p.buf[0..3] == b"ID3" {
        return 100;
    }
    let scan_end = p.buf.len().min(256);
    for i in 0..scan_end.saturating_sub(4) {
        if p.buf[i] == 0xFF
            && (p.buf[i + 1] & 0xE0) == 0xE0
            && parse_frame_header_any_layer(&p.buf[i..i + 4]).is_ok()
        {
            return if i == 0 { 75 } else { 50 };
        }
    }
    if p.ext == Some("mp3") || p.ext == Some("mp2") || p.ext == Some("mp1") {
        // Extension hint — let the demuxer try.
        return 25;
    }
    0
}

fn open(mut input: Box<dyn ReadSeek>) -> Result<Box<dyn Demuxer>> {
    let (mut metadata, mut pictures) = read_id3v2_if_present(&mut input)?;
    let first_offset = input.stream_position()?;
    let (header_bytes, sync_off) = find_first_frame(&mut input)?;
    let hdr = parse_frame_header_any_layer(&header_bytes)?;

    let sample_rate = hdr.sample_rate;
    let channels = hdr.channels();
    let time_base = TimeBase::new(1, sample_rate as i64);

    let mut params = CodecParameters::audio(CodecId::new(hdr.codec_id_str()));
    params.media_type = MediaType::Audio;
    params.sample_rate = Some(sample_rate);
    params.channels = Some(channels);
    params.sample_format = Some(SampleFormat::S16);

    // Container-level duration (lazy; computed on first call to
    // duration_micros() — for now just leave None and let the player
    // estimate from data_end - data_start when implemented).
    let stream = StreamInfo {
        index: 0,
        time_base,
        duration: None,
        start_time: Some(0),
        params,
    };

    let frame_start = first_offset + sync_off as u64;
    input.seek(SeekFrom::Start(frame_start))?;

    // Look for an ID3v1 trailer. Many files pair ID3v2 (rich tag at
    // the head) with ID3v1 (short fallback tag in the last 128
    // bytes); we merge any v1 fields that v2 didn't already supply.
    if let Some(v1_pairs) = try_read_id3v1(&mut input, frame_start)? {
        for (k, v) in v1_pairs {
            if !metadata.iter().any(|(ek, _)| *ek == k) {
                metadata.push((k, v));
            }
        }
    }

    // Reposition cursor at the first audio frame; the v1 probe
    // seeks to the end of file.
    input.seek(SeekFrom::Start(frame_start))?;

    let _ = &mut pictures;
    Ok(Box::new(Mp3Demuxer {
        input,
        stream,
        time_base,
        samples_per_frame: hdr.samples_per_frame() as i64,
        next_pts: 0,
        metadata,
        pictures,
    }))
}

/// Read an ID3v2 tag header at offset 0 if present, parse it, and
/// advance past it. Returns `(metadata_pairs, pictures)`; both will be
/// empty when no tag is present. If the parse fails (bad frame size,
/// truncated tag), falls back to blindly skipping past the tag so
/// playback still works.
type Id3v2Payload = (Vec<(String, String)>, Vec<AttachedPicture>);

fn read_id3v2_if_present(input: &mut Box<dyn ReadSeek>) -> Result<Id3v2Payload> {
    let mut head = [0u8; 10];
    let n = read_up_to(input, &mut head)?;
    if n < 10 || &head[0..3] != b"ID3" {
        input.seek(SeekFrom::Current(-(n as i64)))?;
        return Ok((Vec::new(), Vec::new()));
    }
    let flags = head[5];
    let size = ((head[6] as u32) << 21)
        | ((head[7] as u32) << 14)
        | ((head[8] as u32) << 7)
        | (head[9] as u32);
    let footer = if flags & 0x10 != 0 { 10 } else { 0 };
    // Read the full tag body so we can feed it to the parser. We
    // already consumed the 10-byte header.
    let mut body = vec![0u8; size as usize];
    if input.read_exact(&mut body).is_err() {
        // Truncated tag — skip what we can and return empty.
        input.seek(SeekFrom::Current(footer as i64))?;
        return Ok((Vec::new(), Vec::new()));
    }
    let mut full = Vec::with_capacity(10 + body.len());
    full.extend_from_slice(&head);
    full.extend_from_slice(&body);
    let (metadata, pictures) = match oxideav_id3::parse_tag(&full) {
        Ok((tag, _)) => (
            oxideav_id3::to_key_value_pairs(&tag),
            oxideav_id3::attached_pictures(&tag),
        ),
        Err(_) => (Vec::new(), Vec::new()),
    };
    // Skip the footer (body was already consumed by read_exact).
    if footer > 0 {
        input.seek(SeekFrom::Current(footer as i64))?;
    }
    Ok((metadata, pictures))
}

/// Look for an ID3v1 trailer by seeking to the end of the stream and
/// reading the last 128 bytes. Returns the parsed fields as key/value
/// pairs (ready to merge into the v2 metadata list) or `None` when no
/// trailer is present. Leaves the cursor at end-of-file; the caller
/// must reposition.
fn try_read_id3v1(
    input: &mut Box<dyn ReadSeek>,
    min_safe_pos: u64,
) -> Result<Option<Vec<(String, String)>>> {
    let end = input.seek(SeekFrom::End(0))?;
    if end < 128 {
        return Ok(None);
    }
    let tag_start = end - 128;
    // Defensive: if audio starts after where the v1 tag would begin,
    // the file is pathologically small or malformed — skip.
    if tag_start < min_safe_pos {
        return Ok(None);
    }
    input.seek(SeekFrom::Start(tag_start))?;
    let mut buf = [0u8; 128];
    if input.read_exact(&mut buf).is_err() {
        return Ok(None);
    }
    match oxideav_id3::parse_id3v1(&buf) {
        Some(tag) => Ok(Some(oxideav_id3::to_key_value_pairs(&tag))),
        None => Ok(None),
    }
}

/// Scan up to `MAX_HEADER_SCAN` bytes from the current position looking
/// for the first byte that begins a valid MPEG audio frame header.
/// Returns the four header bytes and the offset (relative to the
/// position at entry) where the sync starts. Leaves the input cursor
/// at end-of-buffer; the caller is responsible for repositioning.
fn find_first_frame(input: &mut Box<dyn ReadSeek>) -> Result<([u8; 4], usize)> {
    let mut buf = vec![0u8; MAX_HEADER_SCAN];
    let n = read_up_to(input, &mut buf)?;
    let buf = &buf[..n];
    let mut i = 0;
    while i + 4 <= buf.len() {
        if buf[i] == 0xFF && (buf[i + 1] & 0xE0) == 0xE0 {
            let head = [buf[i], buf[i + 1], buf[i + 2], buf[i + 3]];
            if parse_frame_header_any_layer(&head).is_ok() {
                return Ok((head, i));
            }
        }
        i += 1;
    }
    Err(Error::invalid(
        "MP3: no MPEG audio sync found in first 256 KB",
    ))
}

fn read_up_to(input: &mut Box<dyn ReadSeek>, buf: &mut [u8]) -> Result<usize> {
    let mut got = 0;
    while got < buf.len() {
        match input.read(&mut buf[got..]) {
            Ok(0) => break,
            Ok(n) => got += n,
            Err(e) if e.kind() == std::io::ErrorKind::Interrupted => continue,
            Err(e) => return Err(e.into()),
        }
    }
    Ok(got)
}

struct Mp3Demuxer {
    input: Box<dyn ReadSeek>,
    stream: StreamInfo,
    time_base: TimeBase,
    samples_per_frame: i64,
    /// Output PTS in samples (advances by samples_per_frame per emitted frame).
    next_pts: i64,
    /// Container-level metadata built from an ID3v2 tag at the head,
    /// optionally merged with an ID3v1 trailer.
    metadata: Vec<(String, String)>,
    /// Attached pictures (cover art) from APIC/PIC frames.
    pictures: Vec<AttachedPicture>,
}

impl Demuxer for Mp3Demuxer {
    fn format_name(&self) -> &str {
        "mp3"
    }

    fn streams(&self) -> &[StreamInfo] {
        std::slice::from_ref(&self.stream)
    }

    fn metadata(&self) -> &[(String, String)] {
        &self.metadata
    }

    fn attached_pictures(&self) -> &[AttachedPicture] {
        &self.pictures
    }

    fn next_packet(&mut self) -> Result<Packet> {
        // Read 4 bytes at the expected frame boundary. If they don't parse
        // as a valid MPEG audio header, resync: scan forward up to
        // `MAX_RESYNC_BYTES` looking for the next sync word. MP3 files
        // frequently contain embedded tags / padding / APE footers between
        // audio frames — bailing on the first stray byte cuts playback off
        // mid-track (this is what mpg123 / ffmpeg / VLC all do).
        let head = match self.read_header_with_resync()? {
            Some(h) => h,
            None => return Err(Error::Eof),
        };
        let hdr = parse_frame_header_any_layer(&head)?;
        let frame_bytes = match hdr.frame_bytes() {
            Some(b) => b as usize,
            None => return Err(Error::unsupported("MP3: free-format streams not supported")),
        };
        if frame_bytes < 4 {
            return Err(Error::invalid("MP3: bogus frame length"));
        }
        let mut data = Vec::with_capacity(frame_bytes);
        data.extend_from_slice(&head);
        data.resize(frame_bytes, 0);
        let body_n = read_up_to(&mut self.input, &mut data[4..])?;
        if body_n < frame_bytes - 4 {
            return Err(Error::Eof);
        }

        let pts = self.next_pts;
        self.next_pts += self.samples_per_frame;
        let mut pkt = Packet::new(0, self.time_base, data);
        pkt.pts = Some(pts);
        pkt.dts = Some(pts);
        pkt.duration = Some(self.samples_per_frame);
        pkt.flags.keyframe = true;
        Ok(pkt)
    }
}

impl Mp3Demuxer {
    /// Read a 4-byte frame header from the current position. If the bytes
    /// don't parse as a valid MPEG audio header, scan forward up to
    /// [`MAX_RESYNC_BYTES`] looking for the next sync word. Returns
    /// `Ok(None)` at EOF, `Ok(Some(header_bytes))` once a valid header
    /// is positioned. Leaves the input cursor right after the returned
    /// 4-byte header on success.
    fn read_header_with_resync(&mut self) -> Result<Option<[u8; 4]>> {
        let mut head = [0u8; 4];
        let n = read_up_to(&mut self.input, &mut head)?;
        if n < 4 {
            return Ok(None);
        }
        if parse_frame_header_any_layer(&head).is_ok() {
            return Ok(Some(head));
        }
        // Resync: byte-shift `head` through the stream until we find a
        // valid sync. This is cheap relative to I/O and tolerates any
        // mid-stream garbage up to the resync cap.
        for _ in 0..MAX_RESYNC_BYTES {
            head[0] = head[1];
            head[1] = head[2];
            head[2] = head[3];
            let mut one = [0u8; 1];
            let got = read_up_to(&mut self.input, &mut one)?;
            if got < 1 {
                return Ok(None);
            }
            head[3] = one[0];
            if parse_frame_header_any_layer(&head).is_ok() {
                return Ok(Some(head));
            }
        }
        // Ran out of resync budget — report end-of-stream. Real mid-file
        // garbage rarely exceeds a few KB; 64 KB is a generous cap.
        Ok(None)
    }
}
