//! MPEG audio (Layer I/II/III) file container.
//!
//! Despite the `mp3` module name, this demuxer covers all three MPEG
//! audio layers — `.mp1`, `.mp2`, and `.mp3` files are all raw streams
//! of MPEG audio frames, typically with an ID3v2 tag prefix and an
//! optional ID3v1 suffix, and they share the same 4-byte frame header
//! format. We read the first frame's layer field and select the matching
//! codec id (`mp1`, `mp2`, or `mp3`) so the registry can dispatch to the
//! right decoder.
//!
//! 1. Skips an ID3v2 prefix if present (extension supports CBR + VBR
//!    files generated by every common encoder).
//! 2. Probes the first valid frame to populate `CodecParameters` with
//!    sample rate + channel count + codec id (mp1/mp2/mp3).
//! 3. Emits each frame as one `Packet` (the downstream decoder consumes
//!    one frame per packet).
//!
//! ID3v1 trailer (last 128 bytes prefixed with `TAG`) is stopped on
//! cleanly when sync search hits end of file.

use std::io::{Read, Seek, SeekFrom};

use oxideav_container::{ContainerRegistry, Demuxer, ProbeData, ReadSeek};
use oxideav_core::{
    CodecId, CodecParameters, Error, MediaType, Packet, Result, SampleFormat, StreamInfo, TimeBase,
};

use crate::frame::parse_frame_header_any_layer;

/// Maximum bytes we'll scan looking for the first valid frame (covers a
/// 256 KB worst-case ID3v2 tag plus padding).
const MAX_HEADER_SCAN: usize = 1 << 18;

pub fn register(reg: &mut ContainerRegistry) {
    reg.register_demuxer("mp3", open);
    reg.register_extension("mp3", "mp3");
    reg.register_extension("mp2", "mp3");
    reg.register_extension("mp1", "mp3");
    reg.register_probe("mp3", probe);
}

/// `ID3` magic at offset 0 (very common) OR an MPEG audio sync byte
/// pattern in the first ~256 bytes. The latter is the only signal for
/// raw MP3 files without ID3v2, which is why we look for the bit
/// pattern: byte 0 = 0xFF, byte 1 has the top 3 bits set
/// (0xE0..=0xFF). Even with that, sync alone is fragile, so we
/// confirm by parsing the next 4-byte header.
fn probe(p: &ProbeData) -> u8 {
    if p.buf.len() >= 10 && &p.buf[0..3] == b"ID3" {
        return 100;
    }
    let scan_end = p.buf.len().min(256);
    for i in 0..scan_end.saturating_sub(4) {
        if p.buf[i] == 0xFF
            && (p.buf[i + 1] & 0xE0) == 0xE0
            && parse_frame_header_any_layer(&p.buf[i..i + 4]).is_ok()
        {
            return if i == 0 { 75 } else { 50 };
        }
    }
    if p.ext == Some("mp3") || p.ext == Some("mp2") || p.ext == Some("mp1") {
        // Extension hint — let the demuxer try.
        return 25;
    }
    0
}

fn open(mut input: Box<dyn ReadSeek>) -> Result<Box<dyn Demuxer>> {
    skip_id3v2_if_present(&mut input)?;
    let first_offset = input.stream_position()?;
    let (header_bytes, sync_off) = find_first_frame(&mut input)?;
    let hdr = parse_frame_header_any_layer(&header_bytes)?;

    let sample_rate = hdr.sample_rate;
    let channels = hdr.channels();
    let time_base = TimeBase::new(1, sample_rate as i64);

    let mut params = CodecParameters::audio(CodecId::new(hdr.codec_id_str()));
    params.media_type = MediaType::Audio;
    params.sample_rate = Some(sample_rate);
    params.channels = Some(channels);
    params.sample_format = Some(SampleFormat::S16);

    // Container-level duration (lazy; computed on first call to
    // duration_micros() — for now just leave None and let the player
    // estimate from data_end - data_start when implemented).
    let stream = StreamInfo {
        index: 0,
        time_base,
        duration: None,
        start_time: Some(0),
        params,
    };

    let frame_start = first_offset + sync_off as u64;
    input.seek(SeekFrom::Start(frame_start))?;

    Ok(Box::new(Mp3Demuxer {
        input,
        stream,
        time_base,
        samples_per_frame: hdr.samples_per_frame() as i64,
        next_pts: 0,
    }))
}

/// Advance past an ID3v2 tag header at offset 0 if present. ID3v2
/// header is 10 bytes: `ID3` magic + version (2) + flags (1) + 4 bytes
/// of synchsafe size (7 bits per byte). Footer extends size by another
/// 10 bytes when bit 4 of flags is set.
fn skip_id3v2_if_present(input: &mut Box<dyn ReadSeek>) -> Result<()> {
    let mut head = [0u8; 10];
    let n = read_up_to(input, &mut head)?;
    if n < 10 || &head[0..3] != b"ID3" {
        input.seek(SeekFrom::Current(-(n as i64)))?;
        return Ok(());
    }
    let flags = head[5];
    let size = ((head[6] as u32) << 21)
        | ((head[7] as u32) << 14)
        | ((head[8] as u32) << 7)
        | (head[9] as u32);
    let footer = if flags & 0x10 != 0 { 10 } else { 0 };
    input.seek(SeekFrom::Current((size + footer) as i64))?;
    Ok(())
}

/// Scan up to `MAX_HEADER_SCAN` bytes from the current position looking
/// for the first byte that begins a valid MPEG audio frame header.
/// Returns the four header bytes and the offset (relative to the
/// position at entry) where the sync starts. Leaves the input cursor
/// at end-of-buffer; the caller is responsible for repositioning.
fn find_first_frame(input: &mut Box<dyn ReadSeek>) -> Result<([u8; 4], usize)> {
    let mut buf = vec![0u8; MAX_HEADER_SCAN];
    let n = read_up_to(input, &mut buf)?;
    let buf = &buf[..n];
    let mut i = 0;
    while i + 4 <= buf.len() {
        if buf[i] == 0xFF && (buf[i + 1] & 0xE0) == 0xE0 {
            let head = [buf[i], buf[i + 1], buf[i + 2], buf[i + 3]];
            if parse_frame_header_any_layer(&head).is_ok() {
                return Ok((head, i));
            }
        }
        i += 1;
    }
    Err(Error::invalid(
        "MP3: no MPEG audio sync found in first 256 KB",
    ))
}

fn read_up_to(input: &mut Box<dyn ReadSeek>, buf: &mut [u8]) -> Result<usize> {
    let mut got = 0;
    while got < buf.len() {
        match input.read(&mut buf[got..]) {
            Ok(0) => break,
            Ok(n) => got += n,
            Err(e) if e.kind() == std::io::ErrorKind::Interrupted => continue,
            Err(e) => return Err(e.into()),
        }
    }
    Ok(got)
}

struct Mp3Demuxer {
    input: Box<dyn ReadSeek>,
    stream: StreamInfo,
    time_base: TimeBase,
    samples_per_frame: i64,
    /// Output PTS in samples (advances by samples_per_frame per emitted frame).
    next_pts: i64,
}

impl Demuxer for Mp3Demuxer {
    fn format_name(&self) -> &str {
        "mp3"
    }

    fn streams(&self) -> &[StreamInfo] {
        std::slice::from_ref(&self.stream)
    }

    fn next_packet(&mut self) -> Result<Packet> {
        let mut head = [0u8; 4];
        let n = read_up_to(&mut self.input, &mut head)?;
        if n < 4 {
            return Err(Error::Eof);
        }
        // Tolerate stray non-sync bytes (e.g. ID3v1 trailer) by stopping
        // at the first invalid header — most MP3 players do the same.
        let hdr = match parse_frame_header_any_layer(&head) {
            Ok(h) => h,
            Err(_) => return Err(Error::Eof),
        };
        let frame_bytes = match hdr.frame_bytes() {
            Some(b) => b as usize,
            None => return Err(Error::unsupported("MP3: free-format streams not supported")),
        };
        if frame_bytes < 4 {
            return Err(Error::invalid("MP3: bogus frame length"));
        }
        let mut data = Vec::with_capacity(frame_bytes);
        data.extend_from_slice(&head);
        data.resize(frame_bytes, 0);
        let body_n = read_up_to(&mut self.input, &mut data[4..])?;
        if body_n < frame_bytes - 4 {
            return Err(Error::Eof);
        }

        let pts = self.next_pts;
        self.next_pts += self.samples_per_frame;
        let mut pkt = Packet::new(0, self.time_base, data);
        pkt.pts = Some(pts);
        pkt.dts = Some(pts);
        pkt.duration = Some(self.samples_per_frame);
        pkt.flags.keyframe = true;
        Ok(pkt)
    }
}
