//! Dump the libvorbis reference setup packet from a .ogg file generated by
//! ffmpeg CLI, as a Rust `&[u8]` literal. Used to bake a real-world setup
//! header into the encoder so we can encode against libvorbis's stock
//! codebooks/floors/residues without having to port them by hand.
//!
//! Usage:
//!   cargo run --example dump_ref_setup -- /tmp/oxideav-vorbis-refs/ref-mono-48k-q3.ogg

fn collect_packets(data: &[u8]) -> Vec<Vec<u8>> {
    let mut out: Vec<Vec<u8>> = Vec::new();
    let mut buf: Vec<u8> = Vec::new();
    let mut i = 0usize;
    while i + 27 <= data.len() {
        if &data[i..i + 4] != b"OggS" {
            break;
        }
        let n_segs = data[i + 26] as usize;
        let lacing = &data[i + 27..i + 27 + n_segs];
        let mut off = i + 27 + n_segs;
        for &lv in lacing {
            buf.extend_from_slice(&data[off..off + lv as usize]);
            off += lv as usize;
            if lv < 255 {
                out.push(std::mem::take(&mut buf));
            }
        }
        i = off;
    }
    if !buf.is_empty() {
        out.push(buf);
    }
    out
}

fn emit_rust_array(name: &str, bytes: &[u8]) {
    println!(
        "/// Raw libvorbis setup packet bytes ({} bytes).",
        bytes.len()
    );
    println!("pub const {}: &[u8] = &[", name);
    for chunk in bytes.chunks(16) {
        print!("    ");
        for b in chunk {
            print!("0x{b:02x}, ");
        }
        println!();
    }
    println!("];");
    println!();
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: dump_ref_setup <path-to-ogg> [const-name]");
        std::process::exit(2);
    }
    let path = &args[1];
    let const_name = args
        .get(2)
        .cloned()
        .unwrap_or_else(|| "REF_SETUP".to_string());
    let data = std::fs::read(path).expect("read ogg");
    let pkts = collect_packets(&data);
    assert!(pkts.len() >= 3, "need id + comment + setup at minimum");
    eprintln!("# found {} packets", pkts.len());
    eprintln!("# id   : {} bytes, magic {:#x}", pkts[0].len(), pkts[0][0]);
    eprintln!("# comm : {} bytes, magic {:#x}", pkts[1].len(), pkts[1][0]);
    eprintln!("# setup: {} bytes, magic {:#x}", pkts[2].len(), pkts[2][0]);
    assert_eq!(pkts[2][0], 0x05, "packet 3 must be setup header");
    emit_rust_array(&const_name, &pkts[2]);
}
